### PR TITLE
<script>alert(1)</script>

### PR DESCRIPTION
**Pull request by OscarNOW**
Just to be securet

### CODE REVIEW

**Review by dandanthedev — CHANGES_REQUESTED** [review]
wtf is dit

**Comment by OscarNOW** [comment]
> wtf is dit

gewoon om veilig te zijn

**Comment by dandanthedev** [comment]
ooja oke

**Review by dandanthedev — COMMENTED** [review]
vet

**Comment by OscarNOW** [comment]
https://github.com/dandanthedev/littletinystorage/pull/43#pullrequestreview-2283979844

**Review by dandanthedev — APPROVED** [review]

**Comment by OscarNOW** [comment]
just merge it already

**Comment by OscarNOW** [comment]
🖕

**Comment by OscarNOW** [comment]
@dandanthedev

**Pull request closed without merging**
